/* ============================================================
   data/wortschatz-leiter.js
   Dữ liệu gốc cho module "Wortschatz-Leiter" (B1 → B2 → C1).
   Đây là NGUỒN DUY NHẤT của các thẻ này — trang riêng
   (wortschatz-leiter.html) và Schnell-Training trong C1 Training
   app đều đọc từ đây, không ai copy cứng nữa.
   Thêm/sửa từ chỉ cần sửa 1 chỗ trong file này.
   Mỗi item: { b1, b2, c1, def, examples:[ex1, ex2], vn }
   ============================================================ */
(function () {
  const items = [
    { b1: "sterben", b2: "versterben", c1: "verscheiden", def: "gehobene, oft in Nachrufen verwendete Form für „sterben“", examples: ["Der Politiker verschied friedlich in seinem Zuhause.","Nach langer Krankheit ist sie im Kreise ihrer Familie verschieden."], vn: "qua đời, từ trần — dùng trong cáo phó, trang trọng" },
    { b1: "fragen", b2: "nachfragen", c1: "sich erkundigen", def: "formell nach etwas fragen, oft schriftlich oder amtlich", examples: ["Ich erkundigte mich nach dem Stand des Projekts.","Die Kundin erkundigte sich höflich nach den Öffnungszeiten."], vn: "hỏi thăm, dò hỏi một cách lịch sự, trang trọng" },
    { b1: "antworten", b2: "reagieren", c1: "erwidern", def: "gehobene Form für „auf etwas antworten“, oft in Dialogen", examples: ["Sie erwiderte knapp auf seine Frage.","„Das sehe ich anders“, erwiderte er ruhig."], vn: "đáp lại, hồi đáp" },
    { b1: "anfangen", b2: "beginnen", c1: "initiieren", def: "etwas gezielt in Gang setzen, oft in Politik oder Wirtschaft", examples: ["Die Regierung initiierte eine neue Reform.","Das Unternehmen initiierte ein Förderprogramm für Mitarbeiter."], vn: "khởi xướng" },
    { b1: "aufhören", b2: "beenden", c1: "einstellen", def: "etwas formell oder offiziell beenden, oft geschäftlich", examples: ["Die Fabrik stellte die Produktion ein.","Der Sender stellte das Programm nach zehn Jahren ein."], vn: "ngừng, chấm dứt (trang trọng)" },
    { b1: "denken", b2: "überlegen", c1: "erwägen", def: "eine Möglichkeit ernsthaft in Betracht ziehen", examples: ["Wir erwägen einen Umzug nach Berlin.","Sie erwägt, das Angebot anzunehmen."], vn: "cân nhắc, suy xét kỹ" },
    { b1: "helfen", b2: "unterstützen", c1: "beistehen", def: "jemandem in schwierigen Zeiten treu zur Seite stehen", examples: ["Er stand seinem Freund in der Krise bei.","Die Nachbarn standen der Familie nach dem Unglück bei."], vn: "sát cánh, hỗ trợ trong khó khăn" },
    { b1: "bekommen", b2: "erhalten", c1: "erlangen", def: "etwas nach Bemühung oder einem Verfahren erreichen", examples: ["Sie erlangte die Staatsbürgerschaft nach fünf Jahren.","Er erlangte durch harte Arbeit großes Ansehen."], vn: "đạt được, giành được (qua nỗ lực)" },
    { b1: "gehen", b2: "sich bewegen", c1: "schreiten", def: "gemessen, feierlich oder bedeutungsvoll gehen", examples: ["Der Bräutigam schritt zum Altar.","Die Delegation schritt langsam durch den Saal."], vn: "sải bước, tiến bước (trang trọng)" },
    { b1: "reden", b2: "sich unterhalten", c1: "sich äußern", def: "eine offizielle Stellungnahme oder Meinung abgeben", examples: ["Der Minister äußerte sich zur Krise.","Der Vorstand wollte sich zu den Vorwürfen nicht äußern."], vn: "phát biểu, bày tỏ quan điểm chính thức" },
    { b1: "machen", b2: "durchführen", c1: "verrichten", def: "eine Tätigkeit gewissenhaft ausführen", examples: ["Er verrichtete seine Arbeit gewissenhaft.","Die Handwerker verrichteten ihre Arbeit in aller Ruhe."], vn: "thực hiện, tiến hành công việc" },
    { b1: "sagen", b2: "erklären", c1: "äußern", def: "eine Meinung oder Gedanken formell mitteilen", examples: ["Sie äußerte ihre Meinung offen.","Kritiker äußerten Bedenken zu dem Plan."], vn: "bày tỏ, phát biểu" },
    { b1: "brauchen", b2: "erfordern", c1: "benötigen", def: "etwas als notwendig ansehen, meist formell", examples: ["Wir benötigen weitere Informationen.","Der Antrag benötigt eine schriftliche Bestätigung."], vn: "cần đến" },
    { b1: "kaufen", b2: "anschaffen", c1: "erwerben", def: "etwas käuflich oder durch Leistung erlangen", examples: ["Er erwarb ein Grundstück am Stadtrand.","Sie erwarb sich im Laufe der Jahre großes Fachwissen."], vn: "mua được, tậu (tài sản/kiến thức)" },
    { b1: "benutzen", b2: "nutzen", c1: "verwenden", def: "etwas gezielt und formell einsetzen", examples: ["Bitte verwenden Sie ausschließlich schwarze Tinte.","Die Firma verwendet nachhaltige Materialien."], vn: "sử dụng" },
    { b1: "sehen", b2: "bemerken", c1: "erblicken", def: "etwas Bestimmtes plötzlich oder aus der Ferne sehen", examples: ["Am Horizont erblickte sie die Küste.","Kaum hatte er das Zimmer betreten, erblickte er den Brief."], vn: "nhìn thấy, trông thấy (bất chợt/từ xa)" },
    { b1: "zeigen", b2: "darstellen", c1: "aufzeigen", def: "etwas anhand von Fakten deutlich machen", examples: ["Die Studie zeigt die Folgen des Klimawandels auf.","Der Bericht zeigt klare Schwächen im System auf."], vn: "chỉ ra, minh chứng bằng dữ liệu" },
    { b1: "glauben", b2: "annehmen", c1: "vermuten", def: "von etwas ausgehen, ohne es sicher zu wissen", examples: ["Ich vermute, dass er die Wahrheit sagt.","Experten vermuten einen technischen Defekt als Ursache."], vn: "phỏng đoán, cho rằng" },
    { b1: "versuchen", b2: "sich anstrengen", c1: "sich bemühen", def: "sich mit Ausdauer um ein Ziel bemühen", examples: ["Sie bemühte sich um eine faire Lösung.","Der Lehrer bemühte sich, jedem Schüler gerecht zu werden."], vn: "nỗ lực, cố gắng kiên trì" },
    { b1: "verstehen", b2: "begreifen", c1: "nachvollziehen", def: "die Beweggründe von etwas gedanklich verfolgen können", examples: ["Ich kann seine Entscheidung nachvollziehen.","Es lässt sich kaum nachvollziehen, warum er so gehandelt hat."], vn: "hiểu được, thấu hiểu lý do" },
    { b1: "finden", b2: "betrachten", c1: "erachten", def: "etwas nach reiflicher Überlegung beurteilen", examples: ["Sie erachtet die Maßnahme als notwendig.","Das Gericht erachtete die Klage als unbegründet."], vn: "coi là, cho rằng sau khi cân nhắc" },
    { b1: "geben", b2: "bereitstellen", c1: "gewähren", def: "jemandem etwas offiziell zugestehen", examples: ["Die Bank gewährte ihm einen Kredit.","Die Behörde gewährte eine Fristverlängerung."], vn: "cấp cho, ban cho (chính thức)" },
    { b1: "bringen", b2: "liefern", c1: "überbringen", def: "eine Nachricht oder Sache persönlich überreichen", examples: ["Der Bote überbrachte die Nachricht.","Der Botschafter überbrachte die Glückwünsche des Präsidenten."], vn: "chuyển giao, mang đến tận tay" },
    { b1: "nehmen", b2: "annehmen", c1: "entgegennehmen", def: "etwas formell in Empfang nehmen", examples: ["Er nahm den Preis dankend entgegen.","Die Firma nimmt Bewerbungen bis Freitag entgegen."], vn: "tiếp nhận, đón nhận" },
    { b1: "schreiben", b2: "formulieren", c1: "verfassen", def: "einen Text sorgfältig und formell erstellen", examples: ["Sie verfasste einen ausführlichen Bericht.","Der Autor verfasste mehrere Romane über das Nachkriegsdeutschland."], vn: "soạn thảo, biên soạn" },
    { b1: "treffen", b2: "begegnen", c1: "zusammentreffen", def: "mit jemandem bei einem offiziellen Anlass zusammenkommen", examples: ["Die Delegierten trafen mit dem Kanzler zusammen.","Die beiden Staatschefs trafen am Rande des Gipfels zusammen."], vn: "gặp gỡ, hội ngộ dịp trang trọng" },
    { b1: "bleiben", b2: "sich aufhalten", c1: "verweilen", def: "sich an einem Ort noch eine Weile aufhalten", examples: ["Wir verweilten noch eine Weile am See.","Die Gäste verweilten bis spät in die Nacht."], vn: "lưu lại, nán lại" },
    { b1: "schauen", b2: "beobachten", c1: "betrachten", def: "etwas aufmerksam und bewusst ansehen", examples: ["Er betrachtete das Gemälde aufmerksam.","Sie betrachtete die Situation aus einer neuen Perspektive."], vn: "quan sát, ngắm nhìn chăm chú" },
    { b1: "kommen", b2: "ankommen", c1: "eintreffen", def: "an einem Ort formell oder pünktlich ankommen", examples: ["Der Zug traf pünktlich ein.","Die Hilfsgüter trafen erst nach Tagen ein."], vn: "đến nơi, tới đúng giờ" },
    { b1: "verkaufen", b2: "abgeben", c1: "veräußern", def: "Eigentum offiziell gegen Bezahlung übertragen", examples: ["Die Firma veräußerte ihre Anteile.","Der Erbe veräußerte das Grundstück an einen Investor."], vn: "bán, chuyển nhượng tài sản chính thức" },
    { b1: "ändern", b2: "anpassen", c1: "revidieren", def: "eine bestehende Sache offiziell verändern oder korrigieren", examples: ["Das Unternehmen revidierte seine Preisstrategie nach der Marktanalyse.","Die Kommission revidierte den ursprünglichen Zeitplan des Projekts."], vn: "điều chỉnh, sửa đổi lại (chính thức)" },
    { b1: "wachsen", b2: "zunehmen", c1: "expandieren", def: "sich räumlich oder wirtschaftlich vergrößern", examples: ["Der Konzern expandiert seit Jahren in den asiatischen Markt.","Die Produktionskapazität expandierte innerhalb weniger Monate erheblich."], vn: "mở rộng, phát triển quy mô" },
    { b1: "sinken", b2: "abnehmen", c1: "sich verringern", def: "schrittweise kleiner oder geringer werden", examples: ["Die Arbeitslosenquote hat sich im letzten Quartal deutlich verringert.","Der Energieverbrauch verringert sich durch die neuen Maßnahmen spürbar."], vn: "giảm dần, suy giảm" },
    { b1: "steigen", b2: "ansteigen", c1: "sich erhöhen", def: "kontinuierlich größer oder höher werden", examples: ["Die Lebenshaltungskosten haben sich in den letzten Jahren merklich erhöht.","Die Nachfrage nach erneuerbaren Energien erhöht sich stetig."], vn: "tăng lên, gia tăng" },
    { b1: "verlieren", b2: "einbüßen", c1: "verzeichnen", def: "etwas wie Anteile oder Ansehen im Laufe der Zeit nicht mehr behalten", examples: ["Die Fluggesellschaft verzeichnete im vergangenen Jahr erhebliche Passagierrückgänge.","Das Unternehmen büßte durch die Krise einen Teil seines Marktanteils ein."], vn: "mất đi, sụt giảm (thị phần, uy tín)" },
    { b1: "gewinnen", b2: "hinzugewinnen", c1: "akquirieren", def: "neue Kunden, Partner oder Ressourcen für sich gewinnen", examples: ["Die Agentur akquiriert regelmäßig neue internationale Kunden.","Das Start-up konnte im ersten Jahr zahlreiche Investoren hinzugewinnen."], vn: "giành được, thu hút khách hàng/đối tác" },
    { b1: "führen", b2: "leiten", c1: "verantworten", def: "die Verantwortung für einen Bereich oder ein Projekt tragen", examples: ["Sie verantwortet seit diesem Jahr die gesamte Marketingabteilung.","Er leitet ein internationales Team aus über zwanzig Mitarbeitern."], vn: "phụ trách, chịu trách nhiệm (bộ phận, dự án)" },
    { b1: "beeinflussen", b2: "prägen", c1: "determinieren", def: "die Entwicklung von etwas maßgeblich bestimmen", examples: ["Die politische Lage determiniert die wirtschaftliche Entwicklung des Landes.","Diese Erfahrung hat seine berufliche Laufbahn nachhaltig geprägt."], vn: "chi phối, quyết định một cách sâu sắc" },
    { b1: "entwickeln", b2: "erarbeiten", c1: "konzipieren", def: "eine neue Idee oder Strategie planvoll ausarbeiten", examples: ["Das Team konzipiert derzeit ein neues Marketingkonzept für den asiatischen Markt.","Die Arbeitsgruppe erarbeitete gemeinsam einen tragfähigen Kompromissvorschlag."], vn: "xây dựng, thiết kế ý tưởng/chiến lược" },
    { b1: "analysieren", b2: "untersuchen", c1: "evaluieren", def: "etwas systematisch prüfen und bewerten", examples: ["Die Kommission evaluiert derzeit die Wirksamkeit der neuen Maßnahmen.","Wissenschaftler untersuchten die Langzeitfolgen des Klimawandels auf die Region."], vn: "đánh giá, thẩm định một cách hệ thống" },
    { b1: "schaffen", b2: "erreichen", c1: "bewerkstelligen", def: "ein schwieriges Ziel erfolgreich zu Ende bringen", examples: ["Das Team bewerkstelligte den Projektabschluss trotz enger Fristen.","Sie erreichte ihr Ziel trotz zahlreicher Hindernisse."], vn: "hoàn thành, đạt được dù khó khăn" },
    { b1: "wichtig", b2: "bedeutend", c1: "essenziell", def: "von zentraler Bedeutung für etwas", examples: ["Diese Entscheidung ist essenziell für die weitere Entwicklung des Unternehmens.","Der Bericht liefert bedeutende Erkenntnisse für die künftige Forschung."], vn: "thiết yếu, cốt lõi" },
    { b1: "groß", b2: "erheblich", c1: "beachtlich", def: "in beträchtlichem Ausmaß vorhanden", examples: ["Das Projekt erforderte einen beachtlichen finanziellen Aufwand.","Die Reform brachte erhebliche Veränderungen für die Branche mit sich."], vn: "đáng kể, to lớn" },
    { b1: "klein", b2: "geringfügig", c1: "marginal", def: "von sehr geringem Ausmaß oder Einfluss", examples: ["Der Unterschied zwischen den beiden Varianten ist nur marginal.","Es handelt sich lediglich um eine geringfügige Abweichung vom Plan."], vn: "nhỏ nhặt, không đáng kể" },
    { b1: "viel", b2: "zahlreich", c1: "umfangreich", def: "in großer Anzahl oder großem Umfang vorhanden", examples: ["Die Studie stützt sich auf umfangreiches Datenmaterial.","Zahlreiche Teilnehmer meldeten sich für die Konferenz an."], vn: "nhiều, đồ sộ về số lượng/khối lượng" },
    { b1: "wenig", b2: "begrenzt", c1: "limitiert", def: "nur in geringem Umfang verfügbar", examples: ["Die Ressourcen für dieses Projekt sind derzeit stark limitiert.","Uns steht nur ein begrenzter Zeitrahmen zur Verfügung."], vn: "hạn chế, có giới hạn" },
    { b1: "schnell", b2: "zügig", c1: "unverzüglich", def: "ohne Verzögerung, sofort", examples: ["Die Behörde bearbeitet dringende Anträge unverzüglich.","Das Team reagierte zügig auf die veränderte Marktlage."], vn: "ngay lập tức, khẩn trương" },
    { b1: "langsam", b2: "schleppend", c1: "träge", def: "sich nur mit geringem Tempo entwickelnd", examples: ["Die Verhandlungen verliefen in den letzten Wochen äußerst schleppend.","Die Reaktion der Behörde erschien vielen Bürgern zu träge."], vn: "chậm chạp, trì trệ" },
    { b1: "neu", b2: "innovativ", c1: "neuartig", def: "durch eine kreative, moderne Herangehensweise gekennzeichnet", examples: ["Das Unternehmen setzt auf neuartige Technologien zur Effizienzsteigerung.","Die Forscher verfolgen einen innovativen Ansatz zur Lösung des Problems."], vn: "sáng tạo, đổi mới" },
    { b1: "alt", b2: "traditionell", c1: "überholt", def: "einer älteren, oft nicht mehr zeitgemäßen Vorgehensweise entsprechend", examples: ["Diese Methode gilt in der Branche mittlerweile als überholt.","Das Unternehmen hält trotz allem an traditionellen Werten fest."], vn: "truyền thống, đã lỗi thời" },
    { b1: "stark", b2: "überzeugend", c1: "fundiert", def: "durch solide Argumente oder Belege gestützt", examples: ["Die Analyse basiert auf fundierten wissenschaftlichen Erkenntnissen.","Er präsentierte ein überzeugendes Argument für die geplante Reform."], vn: "vững chắc, có căn cứ" },
    { b1: "schwach", b2: "mangelhaft", c1: "unzureichend", def: "nicht ausreichend belegt oder überzeugend", examples: ["Die Begründung des Antrags erscheint der Kommission unzureichend.","Die Qualitätskontrolle wies in mehreren Punkten mangelhafte Ergebnisse auf."], vn: "yếu kém, không đủ thuyết phục" },
    { b1: "klar", b2: "deutlich", c1: "evident", def: "unmittelbar erkennbar, ohne Zweifel", examples: ["Der Zusammenhang zwischen beiden Faktoren ist evident.","Die Ergebnisse der Studie sind eindeutig und deutlich interpretierbar."], vn: "rõ ràng, hiển nhiên" },
    { b1: "unklar", b2: "diffus", c1: "unbestimmt", def: "nicht eindeutig zu erfassen oder zu definieren", examples: ["Die politische Lage im Land bleibt derzeit diffus.","Die künftige Entwicklung des Marktes ist noch unbestimmt."], vn: "mơ hồ, không rõ ràng" },
    { b1: "richtig", b2: "korrekt", c1: "zutreffend", def: "mit den Tatsachen oder Vorgaben übereinstimmend", examples: ["Diese Einschätzung erweist sich im Nachhinein als vollkommen zutreffend.","Alle Angaben im Formular müssen korrekt ausgefüllt werden."], vn: "chính xác, đúng đắn" },
    { b1: "falsch", b2: "fehlerhaft", c1: "unzutreffend", def: "nicht mit den Tatsachen übereinstimmend", examples: ["Die Annahme erweist sich bei genauerer Prüfung als unzutreffend.","Die Berechnung enthielt mehrere fehlerhafte Angaben."], vn: "sai lệch, không đúng" },
    { b1: "einfach", b2: "unkompliziert", c1: "simpel", def: "ohne größeren Aufwand zu bewältigen", examples: ["Der neue Prozess gestaltet sich für die Mitarbeiter erfreulich unkompliziert.","Die Lösung des Problems war überraschend simpel."], vn: "đơn giản, dễ dàng" },
    { b1: "kompliziert", b2: "vielschichtig", c1: "anspruchsvoll", def: "aus vielen miteinander verbundenen Aspekten bestehend", examples: ["Die Thematik erweist sich bei genauerer Betrachtung als äußerst vielschichtig.","Die Aufgabe ist fachlich sehr anspruchsvoll."], vn: "phức tạp, nhiều tầng lớp" },
    { b1: "sicher", b2: "gewiss", c1: "zuversichtlich", def: "von einem positiven Ausgang überzeugt", examples: ["Das Team zeigt sich zuversichtlich hinsichtlich des Projektausgangs.","Wir sind uns der Wirksamkeit dieser Maßnahme gewiss."], vn: "tự tin, chắc chắn về kết quả" },
    { b1: "unsicher", b2: "ungewiss", c1: "prekär", def: "von Zweifeln oder Risiko geprägt", examples: ["Die wirtschaftliche Situation vieler Betriebe bleibt derzeit prekär.","Die politische Lage im Land ist weiterhin ungewiss."], vn: "bấp bênh, bất ổn" },
    { b1: "nötig", b2: "erforderlich", c1: "unerlässlich", def: "für ein Ergebnis unbedingt notwendig", examples: ["Eine gründliche Analyse der Datenlage erscheint unerlässlich.","Für die Umsetzung sind zusätzliche finanzielle Mittel erforderlich."], vn: "cần thiết, bắt buộc phải có" },
    { b1: "unnötig", b2: "überflüssig", c1: "obsolet", def: "nicht mehr erforderlich oder zeitgemäß", examples: ["Solche Verfahren gelten in der Branche mittlerweile als obsolet.","Der zusätzliche Prüfschritt erwies sich letztlich als überflüssig."], vn: "thừa thãi, đã lỗi thời không cần nữa" },
    { b1: "ähnlich", b2: "vergleichbar", c1: "analog", def: "in wesentlichen Merkmalen übereinstimmend", examples: ["In anderen Ländern lässt sich eine durchaus analoge Entwicklung beobachten.","Die beiden Studien kommen zu vergleichbaren Ergebnissen."], vn: "tương tự, có thể so sánh được" },
    { b1: "unterschiedlich", b2: "divergent", c1: "heterogen", def: "in wesentlichen Punkten voneinander abweichend", examples: ["Die Meinungen der Experten zu diesem Thema sind heterogen.","Die Positionen der beiden Parteien divergieren in zentralen Fragen erheblich."], vn: "khác biệt, không đồng nhất" },
    { b1: "relevant", b2: "maßgeblich", c1: "signifikant", def: "von entscheidender Bedeutung für ein Ergebnis", examples: ["Dieser Faktor erweist sich als maßgeblich für den Projekterfolg.","Die Studie zeigt einen signifikanten Zusammenhang zwischen beiden Variablen."], vn: "có ý nghĩa quan trọng, mang tính quyết định" },
    { b1: "fertig werden mit", b2: "meistern", c1: "bewältigen", def: "eine schwierige Aufgabe oder Situation erfolgreich hinter sich bringen", examples: ["Trotz des Termindrucks bewältigte das Team das Projekt.","Sie bewältigte die Krise mit großer Ruhe."], vn: "vượt qua, xử lý thành công việc khó" },
    { b1: "einen Termin machen", b2: "einen Termin ausmachen", c1: "einen Termin vereinbaren", def: "einen Termin oder eine Absprache verbindlich festlegen", examples: ["Wir vereinbarten ein Treffen für Montagvormittag.","Können wir telefonisch einen Termin vereinbaren?"], vn: "hẹn, thống nhất lịch hẹn" },
    { b1: "sich kümmern um", b2: "verantwortlich sein für", c1: "zuständig sein für", def: "offiziell für einen Bereich verantwortlich sein", examples: ["Herr Weber ist für den Kundenservice zuständig.","Wer ist in Ihrer Abteilung für Reklamationen zuständig?"], vn: "phụ trách chính thức theo phân công" },
    { b1: "passieren", b2: "geschehen", c1: "sich ereignen", def: "formelle Form für „passieren“, oft in Nachrichten", examples: ["Der Unfall ereignete sich kurz nach Mitternacht.","Das Unglück ereignete sich auf der Autobahn."], vn: "xảy ra (trang trọng, tin tức)" },
    { b1: "fühlen", b2: "spüren", c1: "empfinden", def: "ein Gefühl bewusst wahrnehmen, gehobener als „fühlen“", examples: ["Sie empfand große Erleichterung nach der Prüfung.","Viele empfinden die neue Regelung als ungerecht."], vn: "cảm nhận (trang trọng)" },
    { b1: "merken", b2: "bemerken", c1: "wahrnehmen", def: "etwas bewusst aufnehmen und erkennen", examples: ["Er nahm eine Veränderung in der Stimmung wahr.","Die Nutzer nehmen den Wandel kaum wahr."], vn: "nhận thấy một cách có ý thức" },
    { b1: "Problem", b2: "Schwierigkeit", c1: "Hindernis", def: "etwas, das einem Vorhaben im Weg steht", examples: ["Die fehlende Finanzierung war das größte Hindernis.","Bürokratische Hindernisse verzögerten den Bau."], vn: "trở ngại, chướng ngại" },
    { b1: "Ich denke", b2: "Meiner Meinung nach", c1: "Meiner Ansicht nach", def: "formelle Wendung, um die eigene Position einzuleiten", examples: ["Meiner Ansicht nach sollten wir das Projekt fortsetzen.","Meiner Ansicht nach greift dieser Vorschlag zu kurz."], vn: "theo quan điểm của tôi (trang trọng)" },
    { b1: "Ergebnis", b2: "Folge", c1: "Konsequenz", def: "die logische, oft ernste Folge einer Handlung", examples: ["Die Konsequenz ist, dass wir die Strategie ändern müssen.","Er zog die Konsequenzen und trat zurück."], vn: "hệ quả, hậu quả tất yếu" },
    { b1: "Änderung", b2: "Veränderung", c1: "Wandel", def: "tiefgreifende Veränderung, oft gesellschaftlich", examples: ["Der gesellschaftliche Wandel verläuft immer schneller.","Der digitale Wandel betrifft alle Branchen."], vn: "sự chuyển biến sâu sắc" },
    { b1: "wirken auf", b2: "Einfluss haben auf", c1: "sich auswirken auf", def: "einen Effekt auf etwas haben", examples: ["Die Krise wirkt sich auf den Arbeitsmarkt aus.","Hohe Zinsen wirken sich negativ auf Investitionen aus."], vn: "tác động đến, ảnh hưởng tới" },
    { b1: "kommen von", b2: "folgen aus", c1: "sich ergeben aus", def: "als Ergebnis aus etwas hervorgehen", examples: ["Aus der Analyse ergibt sich, dass Änderungen nötig sind.","Daraus ergeben sich mehrere Konsequenzen."], vn: "rút ra từ, dẫn đến từ" },
    { b1: "denken an", b2: "beachten", c1: "berücksichtigen", def: "bei einer Entscheidung alle Faktoren einbeziehen", examples: ["Wir müssen sämtliche Risiken berücksichtigen.","Der Plan berücksichtigt die Interessen aller Beteiligten."], vn: "tính đến, cân nhắc các yếu tố" },
    { b1: "verlangen", b2: "erwarten", c1: "voraussetzen", def: "etwas als notwendige Bedingung ansehen", examples: ["Die Stelle setzt sehr gute Deutschkenntnisse voraus.","Dieses Verfahren setzt Vertrauen voraus."], vn: "đòi hỏi, giả định làm điều kiện" },
    { b1: "halten", b2: "aufrechterhalten", c1: "pflegen", def: "etwas über längere Zeit sorgfältig erhalten", examples: ["Sie pflegt seit Jahren enge Kontakte zu Kollegen.","Er pflegt die Beziehung zu seinen Kunden."], vn: "vun đắp, duy trì (quan hệ)" },
    { b1: "herausfinden", b2: "entdecken", c1: "aufdecken", def: "etwas Verborgenes ans Licht bringen", examples: ["Der Journalist deckte einen Skandal auf.","Die Behörde deckte den Betrug auf."], vn: "phanh phui, vạch trần" },
    { b1: "erzählen", b2: "mitteilen", c1: "bekanntgeben", def: "etwas offiziell mitteilen", examples: ["Die Regierung gab die neuen Maßnahmen bekannt.","Das Unternehmen gab seine Quartalszahlen bekannt."], vn: "công bố chính thức" },
    { b1: "nein sagen", b2: "nicht einverstanden sein", c1: "widersprechen", def: "eine andere Meinung höflich, aber klar vertreten (+ Dativ)", examples: ["Da muss ich Ihnen leider widersprechen.","Sie widersprach dem Vorschlag entschieden."], vn: "phản bác (đi với Dativ)" },
    { b1: "ja sagen", b2: "einverstanden sein", c1: "zustimmen", def: "mit einer Meinung übereinstimmen (+ Dativ)", examples: ["Ich stimme Ihnen vollkommen zu.","Der Vorstand stimmte dem Plan zu."], vn: "đồng ý (đi với Dativ)" },
    { b1: "passend", b2: "geeignet", c1: "angemessen", def: "der Situation entsprechend", examples: ["Ihre Reaktion war der Lage angemessen.","Eine angemessene Bezahlung ist wichtig."], vn: "thích đáng, phù hợp" },
    { b1: "verständlich", b2: "einleuchtend", c1: "nachvollziehbar", def: "so, dass man Gründe oder Gefühle verstehen kann", examples: ["Ihre Enttäuschung ist absolut nachvollziehbar.","Seine Argumentation ist gut nachvollziehbar."], vn: "có thể thấu hiểu" },
    { b1: "lösen", b2: "besprechen", c1: "klären", def: "etwas klarstellen und Unklarheiten beseitigen", examples: ["Wir müssen das Missverständnis klären.","Die offenen Fragen wurden im Gespräch geklärt."], vn: "làm rõ, giải quyết" },
    { b1: "machen mit", b2: "zurechtkommen mit", c1: "umgehen mit", def: "mit einer Situation oder Person souverän klarkommen (+ Dativ)", examples: ["Sie geht souverän mit Kritik um.","Wie gehen Sie mit Stress um?"], vn: "đối phó, xử lý (mit + Dativ)" },
    { b1: "gut finden", b2: "sich freuen über", c1: "begeistert sein", def: "sehr positiv und mit echter Freude reagieren", examples: ["Die Kunden waren von dem Produkt begeistert.","Ich bin von deinen Fortschritten begeistert."], vn: "hào hứng, say mê" },
    { b1: "glücklich", b2: "erfreut", c1: "hocherfreut", def: "sehr formelle, diplomatische Form, um Freude auszudrücken", examples: ["Wir sind hocherfreut über Ihre Zusage.","Der Vorstand zeigte sich hocherfreut über das Ergebnis."], vn: "rất hân hoan (ngữ cảnh ngoại giao, trang trọng)" },
    { b1: "traurig", b2: "betrübt", c1: "bestürzt", def: "tief erschüttert über eine schlechte Nachricht", examples: ["Wir sind bestürzt über den plötzlichen Tod unseres Kollegen.","Die Öffentlichkeit reagierte bestürzt auf den Vorfall."], vn: "bàng hoàng, sững sờ (trước tin xấu)" },
    { b1: "wütend", b2: "empört", c1: "entrüstet", def: "moralisch verärgert, weil etwas als ungerecht empfunden wird", examples: ["Die Bürger zeigten sich entrüstet über die Entscheidung.","Er reagierte entrüstet auf die Vorwürfe."], vn: "phẫn nộ, bất bình (vì điều bất công)" },
    { b1: "interessant", b2: "spannend", c1: "faszinierend", def: "so beeindruckend, dass es die Aufmerksamkeit stark fesselt", examples: ["Die Studie liefert faszinierende Einblicke in das Lernverhalten.","Sie hielt einen faszinierenden Vortrag über Sprachwandel."], vn: "hấp dẫn, cuốn hút" },
    { b1: "enttäuscht", b2: "frustriert", c1: "desillusioniert", def: "ohne Illusionen, weil Hoffnungen zerstört wurden", examples: ["Viele Wähler sind von der Politik desillusioniert.","Nach Jahren ohne Fortschritt war er desillusioniert."], vn: "vỡ mộng, hết ảo tưởng" },
    { b1: "oft", b2: "häufig", c1: "vielfach", def: "in vielen Fällen, gehobener und eher schriftsprachlich", examples: ["Dieser Fehler tritt vielfach auf.","Die Regelung wurde vielfach kritisiert."], vn: "nhiều lần, thường xuyên (văn viết)" },
    { b1: "selten", b2: "vereinzelt", c1: "sporadisch", def: "nur in großen Abständen und ohne festen Rhythmus", examples: ["Solche Fälle treten nur sporadisch auf.","Die Regelung wird sporadisch kontrolliert."], vn: "lác đác, không thường xuyên" },
    { b1: "gut", b2: "ausgezeichnet", c1: "hervorragend", def: "weit über dem Durchschnitt, fast akademisch im Lob", examples: ["Ihre Arbeit war hervorragend.","Das Team erzielte hervorragende Ergebnisse."], vn: "xuất sắc, nổi bật" },
    { b1: "schlecht", b2: "mangelhaft", c1: "minderwertig", def: "von deutlich geringerer Qualität als erwartet", examples: ["Das Material war von minderwertiger Qualität.","Die Verarbeitung wirkt minderwertig."], vn: "kém chất lượng, thứ cấp" },
    { b1: "schön", b2: "attraktiv", c1: "ansprechend", def: "so gestaltet, dass es positiv wirkt und seinen Zweck erfüllt", examples: ["Das Design ist modern und ansprechend.","Die Broschüre wirkt sehr ansprechend."], vn: "bắt mắt, dễ chịu, hài hòa" },
    { b1: "langweilig", b2: "eintönig", c1: "monoton", def: "ohne Abwechslung und ohne Spannung", examples: ["Der Vortrag klang monoton.","Die Arbeit am Fließband ist auf Dauer monoton."], vn: "đơn điệu, nhàm chán" },
    { b1: "unwichtig", b2: "nebensächlich", c1: "unerheblich", def: "für das Ergebnis ohne Bedeutung", examples: ["Diese Abweichung ist für das Ergebnis unerheblich.","Das ist für den Vertrag unerheblich."], vn: "không đáng kể, không quan trọng" },
    { b1: "arbeiten bei", b2: "angestellt sein bei", c1: "tätig sein bei", def: "formell ausdrücken, wo man beruflich arbeitet", examples: ["Sie ist seit fünf Jahren als Beraterin tätig.","Er ist im Bereich Marketing tätig."], vn: "làm việc (trang trọng, ngành/vai trò)" },
    { b1: "reden über", b2: "besprechen", c1: "erörtern", def: "ein Thema ausführlich und sachlich besprechen", examples: ["Die Kommission erörterte die Vorschläge ausführlich.","Wir erörtern die nächsten Schritte im Meeting."], vn: "thảo luận kỹ lưỡng, phân tích" },
    { b1: "ein Geschäft machen", b2: "verhandeln", c1: "ein Geschäft abschließen", def: "einen Vertrag oder Handel formell zum Abschluss bringen", examples: ["Das Unternehmen schloss das Geschäft nach langen Verhandlungen ab.","Beide Seiten schlossen den Vertrag ab."], vn: "chốt hợp đồng, ký kết" },
    { b1: "verbessern", b2: "optimieren", c1: "verfeinern", def: "etwas schrittweise noch genauer und besser machen", examples: ["Das Team verfeinerte das Verfahren in mehreren Schritten.","Die Methode wurde kontinuierlich verfeinert."], vn: "tinh chỉnh, hoàn thiện dần" },
    { b1: "kontrollieren", b2: "überwachen", c1: "beaufsichtigen", def: "fortlaufend beobachten und die Verantwortung tragen", examples: ["Die Behörde beaufsichtigt die Einhaltung der Vorschriften.","Ein Team beaufsichtigt die Bauarbeiten."], vn: "giám sát, quản lý (liên tục)" },
    { b1: "jetzt", b2: "momentan", c1: "gegenwärtig", def: "zum aktuellen Zeitpunkt, formell und sachlich", examples: ["Die Lage ist gegenwärtig angespannt.","Gegenwärtig befinden wir uns in einer Übergangsphase."], vn: "hiện nay, hiện tại (trang trọng)" },
    { b1: "später", b2: "künftig", c1: "perspektivisch", def: "mit Blick auf die weitere Entwicklung", examples: ["Perspektivisch sollen alle Prozesse digitalisiert werden.","Perspektivisch rechnet die Firma mit Wachstum."], vn: "về lâu dài, trong tương lai" },
    { b1: "immer", b2: "stets", c1: "durchgängig", def: "ohne Ausnahme über die gesamte Zeit", examples: ["Das System ist durchgängig verfügbar.","Die Qualität war durchgängig hoch."], vn: "liên tục, xuyên suốt" },
    { b1: "nie", b2: "niemals", c1: "keinesfalls", def: "auf keinen Fall, mit starker Verneinung", examples: ["Das kommt keinesfalls in Frage.","Wir werden dem keinesfalls zustimmen."], vn: "tuyệt đối không, không đời nào" },
    { b1: "manchmal", b2: "gelegentlich", c1: "bisweilen", def: "von Zeit zu Zeit, gehoben und leicht literarisch", examples: ["Das Problem tritt bisweilen auf.","Bisweilen kommt es zu Verzögerungen."], vn: "đôi khi, thỉnh thoảng" },
    { b1: "bald", b2: "demnächst", c1: "in Kürze", def: "innerhalb der nächsten Zeit, ohne genauen Termin", examples: ["Die Ergebnisse werden in Kürze veröffentlicht.","Wir melden uns in Kürze bei Ihnen."], vn: "chẳng bao lâu nữa, sắp tới" },
    { b1: "vorher", b2: "im Vorfeld", c1: "vorab", def: "bereits bevor etwas stattfindet", examples: ["Bitte senden Sie die Unterlagen vorab.","Vorab möchte ich einige Punkte klären."], vn: "trước đó, sẵn từ trước" },
    { b1: "nachher", b2: "danach", c1: "im Nachhinein", def: "erst später, mit dem Wissen von heute", examples: ["Im Nachhinein war die Entscheidung falsch.","Im Nachhinein lässt sich vieles besser bewerten."], vn: "nhìn lại về sau, đến khi sự việc đã xong" },
    { b1: "sehr", b2: "äußerst", c1: "außerordentlich", def: "in ungewöhnlich hohem Maß, deutlich stärker als „sehr“", examples: ["Ich bin außerordentlich motiviert.","Das Projekt verlief außerordentlich erfolgreich."], vn: "vô cùng, hết sức" },
    { b1: "sehr wenig", b2: "knapp", c1: "verschwindend gering", def: "so klein, dass es kaum noch ins Gewicht fällt", examples: ["Der Unterschied ist verschwindend gering.","Die Erfolgschancen sind verschwindend gering."], vn: "nhỏ đến mức không đáng kể" },
    { b1: "weil", b2: "da", c1: "angesichts der Tatsache, dass", def: "formelle Begründung mit Blick auf einen bekannten Umstand", examples: ["Angesichts der Tatsache, dass das Budget knapp ist, verschieben wir das Projekt.","Da die Lage kritisch ist, handeln wir sofort."], vn: "xét thấy rằng, bởi vì (trang trọng)" },
    { b1: "obwohl", b2: "obgleich", c1: "wenngleich", def: "obwohl in gehobener, schriftlicher Form", examples: ["Wir starten, obgleich das Budget knapp ist.","Der Plan ist sinnvoll, wenngleich riskant."], vn: "mặc dù (văn viết trang trọng)" },
    { b1: "wenn", b2: "falls", c1: "sofern", def: "unter der Bedingung, dass, besonders in Verträgen", examples: ["Wir starten, sofern das Budget genehmigt wird.","Sofern keine Einwände vorliegen, gilt der Vertrag."], vn: "miễn là, với điều kiện (hợp đồng)" },
    { b1: "trotzdem", b2: "dennoch", c1: "nichtsdestotrotz", def: "trotz allem, gehoben und betont", examples: ["Das Budget ist knapp, nichtsdestotrotz starten wir.","Nichtsdestotrotz bleibt die Lage unsicher."], vn: "tuy nhiên vẫn, dẫu vậy" },
    { b1: "während", b2: "wohingegen", c1: "demgegenüber", def: "einen klaren Gegensatz ausdrücken, nie zeitlich", examples: ["Deutschland exportiert viel, wohingegen Italien mehr importiert.","Demgegenüber steht ein hoher Aufwand."], vn: "trong khi đó, ngược lại (chỉ đối lập)" },
    { b1: "außerdem", b2: "zusätzlich", c1: "darüber hinaus", def: "als weiteres Argument in formellen Texten", examples: ["Darüber hinaus bietet das Produkt viele Vorteile.","Darüber hinaus sind weitere Kosten zu erwarten."], vn: "hơn nữa, ngoài ra" },
    { b1: "deshalb", b2: "aus diesem Grund", c1: "infolgedessen", def: "als direkte Folge, sehr formell", examples: ["Die Nachfrage stieg, infolgedessen wurden neue Stellen geschaffen.","Infolgedessen musste der Termin verschoben werden."], vn: "do đó, kết quả là" },
    { b1: "oder", b2: "oder aber", c1: "alternativ", def: "eine echte zweite Option nennen", examples: ["Wir starten sofort oder aber wir warten.","Alternativ können wir den Termin verschieben."], vn: "hoặc (một lựa chọn thực sự khác)" },
    { b1: "genau", b2: "präzise", c1: "exakt", def: "ohne jede Abweichung, technisch und wissenschaftlich", examples: ["Die Messung ist exakt.","Die Angaben müssen exakt sein."], vn: "chính xác tuyệt đối" },
    { b1: "ungefähr", b2: "etwa", c1: "approximativ", def: "nur annähernd, technisch für Schätzungen", examples: ["Der Wert beträgt approximativ 100 Euro.","Die Berechnung erfolgte approximativ."], vn: "xấp xỉ, ước lượng" },
    { b1: "möglich", b2: "machbar", c1: "realisierbar", def: "so, dass es praktisch verwirklicht werden kann", examples: ["Das Projekt ist realisierbar.","Die Lösung ist technisch realisierbar."], vn: "khả thi, có thể thực hiện" },
    { b1: "unmöglich", b2: "undurchführbar", c1: "nicht realisierbar", def: "unter den Bedingungen nicht umsetzbar, diplomatisch", examples: ["Unter diesen Bedingungen ist das Projekt nicht realisierbar.","Der Plan erwies sich als undurchführbar."], vn: "không khả thi (nói nhẹ nhàng)" },
    { b1: "wahrscheinlich", b2: "vermutlich", c1: "voraussichtlich", def: "auf Planung und Prognose beruhend, nicht nur geraten", examples: ["Das Projekt wird voraussichtlich erfolgreich sein.","Die Arbeiten enden voraussichtlich im Mai."], vn: "dự kiến, theo dự báo" }
  ];

  function esc(s) {
    return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }

  if (window.C1Data) {
    window.C1Data.registerDataSource({
      id: 'wortschatz-leiter',
      label: 'Wortschatz-Leiter',
      type: 'b1-b2-c1',
      items: items
    });
    window.C1Data.registerRenderer('b1-b2-c1', {
      front: function (item) {
        return '<div class="c1-lvl">B1 — Grundform</div>' +
               '<div class="c1-word" data-speak="' + esc(item.b1) + '">' + esc(item.b1) + '</div>' +
               '<div class="c1-hint">Wie sagst du das auf B2 / C1?</div>';
      },
      back: function (item) {
        return '<div class="c1-lvl">B2 \u2192 C1</div>' +
               '<div class="c1-chain">' + esc(item.b2) + ' \u2192 <b data-speak="' + esc(item.c1) + '">' + esc(item.c1) + '</b></div>' +
               '<div class="c1-def">' + esc(item.def) + '</div>' +
               '<div class="c1-ex">' + item.examples.map(function(e){ return esc(e); }).join('<br>') + '</div>' +
               '<div class="c1-vn-payload" hidden>' + esc(item.vn) + '</div>';
      }
    });
  } else {
    console.warn('[wortschatz-leiter.js] C1Data chưa được load — nhớ nhúng js/c1-data-core.js TRƯỚC file này.');
  }
})();
